language: ruby

rvm:
 - 2.4.0

 services:
 - postgresql

 before_script:
 - psql -c 'create database acebook_database_test;' -U postgres
 - ./bin/server db:migrate

test:
  adapter: postgresql
  database: acebook_database_test

addons:
  postgresql: "9.6.4"